# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startstop.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 732)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.channel1_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel1_chk.setEnabled(True)
        self.channel1_chk.setChecked(True)
        self.channel1_chk.setTristate(False)
        self.channel1_chk.setObjectName("channel1_chk")
        self.verticalLayout_3.addWidget(self.channel1_chk)
        self.channel2_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel2_chk.setEnabled(False)
        self.channel2_chk.setCheckable(True)
        self.channel2_chk.setChecked(True)
        self.channel2_chk.setTristate(False)
        self.channel2_chk.setObjectName("channel2_chk")
        self.verticalLayout_3.addWidget(self.channel2_chk)
        self.channel3_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel3_chk.setEnabled(False)
        self.channel3_chk.setChecked(True)
        self.channel3_chk.setObjectName("channel3_chk")
        self.verticalLayout_3.addWidget(self.channel3_chk)
        self.channel4_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel4_chk.setEnabled(False)
        self.channel4_chk.setChecked(True)
        self.channel4_chk.setObjectName("channel4_chk")
        self.verticalLayout_3.addWidget(self.channel4_chk)
        self.channel5_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel5_chk.setEnabled(False)
        self.channel5_chk.setChecked(True)
        self.channel5_chk.setObjectName("channel5_chk")
        self.verticalLayout_3.addWidget(self.channel5_chk)
        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setIcon(QtGui.QIcon('Icons/right-triangular-arrowhead'))
        self.actionStart.setEnabled(True)
        self.actionStart.setObjectName("actionStart")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setIcon(QtGui.QIcon('Icons/pause-symbol'))
        self.actionPause.setObjectName("actionPause")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setIcon(QtGui.QIcon('Icons/plus-sign'))
        self.actionAdd.setObjectName("actionAdd")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setIcon(QtGui.QIcon('Icons/circle-of-arrows-couple'))
        self.actionReset.setObjectName("actionReset")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setIcon(QtGui.QIcon('Icons/trash-can-with-cover-from-side-view'))
        self.actionDelete.setObjectName("actionDelete")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setIcon(QtGui.QIcon('Icons/open-black-folder-interface-symbol'))
        self.actionLoad.setObjectName("actionLoad")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setIcon(QtGui.QIcon("Icons/plus-zoom-magnifying-glass-interface-symbol"))
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setIcon(QtGui.QIcon('Icons/magnifying-glass-with-minus-sign'))
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setIcon(QtGui.QIcon('Icons/square-of-rounded-corners'))
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoomOut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wave Yeeter"))
        self.groupBox.setTitle(_translate("MainWindow", "Active Channel"))
        self.channel1_chk.setText(_translate("MainWindow", "Channel 1"))
        self.channel2_chk.setText(_translate("MainWindow", "Channel 2 "))
        self.channel3_chk.setText(_translate("MainWindow", "Channel 3"))
        self.channel4_chk.setText(_translate("MainWindow", "Channel 4"))
        self.channel5_chk.setText(_translate("MainWindow", "Channel 5 "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setToolTip(_translate("MainWindow", "Play Signal"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause Signal"))
        self.actionAdd.setText(_translate("MainWindow", "Add Panel"))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add Panel"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset App from Beginning"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setToolTip(_translate("MainWindow", "Remove Signal"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setToolTip(_translate("MainWindow", "Load Signal"))
        self.actionZoomIn.setText(_translate("MainWindow", "ZoomIn"))
        self.actionZoomIn.setToolTip(_translate("MainWindow", "Zoom In"))
        self.actionZoomOut.setText(_translate("MainWindow", "ZoomOut"))
        self.actionZoomOut.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

