# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startstop.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 915, 761))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = PlotWidget(self.scrollAreaWidgetContents)
        self.widget.setEnabled(True)
        self.widget.setMinimumSize(QtCore.QSize(500, 300))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.channel1_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel1_chk.setChecked(True)
        self.channel1_chk.setTristate(False)
        self.channel1_chk.setObjectName("channel1_chk")
        self.verticalLayout_3.addWidget(self.channel1_chk)
        self.channel2_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel2_chk.setEnabled(True)
        self.channel2_chk.setCheckable(True)
        self.channel2_chk.setChecked(True)
        self.channel2_chk.setObjectName("channel2_chk")
        self.verticalLayout_3.addWidget(self.channel2_chk)
        self.channel3_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel3_chk.setChecked(True)
        self.channel3_chk.setObjectName("channel3_chk")
        self.verticalLayout_3.addWidget(self.channel3_chk)
        self.channel4_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel4_chk.setChecked(True)
        self.channel4_chk.setObjectName("channel4_chk")
        self.verticalLayout_3.addWidget(self.channel4_chk)
        self.channel5_chk = QtWidgets.QCheckBox(self.groupBox)
        self.channel5_chk.setChecked(True)
        self.channel5_chk.setObjectName("channel5_chk")
        self.verticalLayout_3.addWidget(self.channel5_chk)
        self.zoom = QtWidgets.QPushButton(self.groupBox)
        self.zoom.setObjectName("zoom")
        self.verticalLayout_3.addWidget(self.zoom)
        self.horizontalLayout_5.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setIcon(QtGui.QIcon('Icons/right-triangular-arrowhead'))
        self.actionStart.setEnabled(True)
        self.actionStart.setObjectName("actionStart")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setIcon(QtGui.QIcon('Icons/pause-symbol'))
        self.actionPause.setObjectName("actionPause")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setIcon(QtGui.QIcon('Icons/plus-sign'))
        self.actionAdd.setObjectName("actionAdd")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setIcon(QtGui.QIcon('Icons/circle-of-arrows-couple'))
        self.actionReset.setObjectName("actionReset")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setIcon(QtGui.QIcon('Icons/trash-can-with-cover-from-side-view'))
        self.actionDelete.setObjectName("actionDelete")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setIcon(QtGui.QIcon('Icons/open-black-folder-interface-symbol'))
        self.actionLoad.setObjectName("actionLoad")
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionLoad)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Active Channel"))
        self.channel1_chk.setText(_translate("MainWindow", "Channel 1"))
        self.channel2_chk.setText(_translate("MainWindow", "Channel 2 "))
        self.channel3_chk.setText(_translate("MainWindow", "Channel 3"))
        self.channel4_chk.setText(_translate("MainWindow", "Channel 4"))
        self.channel5_chk.setText(_translate("MainWindow", "Channel 5 "))
        self.zoom.setText(_translate("MainWindow", "zoom"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionStart.setToolTip(_translate("MainWindow", "Play Signal"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause Signal"))
        self.actionAdd.setText(_translate("MainWindow", "Add Panel"))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add Panel"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset Signal from Beginning"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setToolTip(_translate("MainWindow", "Remove Signal"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setToolTip(_translate("MainWindow", "Load Signal"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

